# automically run test for labs, python and go environment is needed 

name: auto-judge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lab3:
    name: judge for lab3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install telegram bot dependencies
      run: python -m pip install --upgrade pip python-telegram-bot

    - name: Run test
      run: |
        cd ./src/raft
        python3 judge.py --count 20 --pattern '3[ABCD]$' --race --telegram-token ${{ secrets.TELEGRAM_TOKEN }} --telegram-chatid ${{ secrets.TELEGRAM_CHATID }}
  
  lab4:
    name: judge for lab4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
      
    - name: Install telegram bot dependencies
      run: python -m pip install --upgrade pip python-telegram-bot
    
    - name: Run test
      run: |
        cd ./src/kvraft
        python3 judge.py --count 20 --pattern '4A' --race --telegram-token ${{ secrets.TELEGRAM_TOKEN }} --telegram-chatid ${{ secrets.TELEGRAM_CHATID }}