# automically run test for lab 3, python and go environment is needed 

name: lab3 judge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run test
      run: |
        python3 ./src/raft/judge.py --count 200 --pattern 'TestSnapshotInstall3D' --race

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
